name: decoder 
base: core22
adopt-info: decoder
grade: stable
confinement: strict

parts:
  pipewire:
    source: https://gitlab.freedesktop.org/pipewire/pipewire.git
    source-tag: '0.3.80'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dexamples=disabled
      - -Dtests=disabled
      - -Dman=disabled
      - -Dgstreamer=enabled
      - -Dgstreamer-device-provider=enabled
    prime:
      - -usr/lib/*/pkgconfig
      - -usr/include

  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: ''

  deps:
    plugin: nil
    stage-packages:
      - libzbar0
      - gstreamer1.0-gl
      - libgstreamer-gl1.0-0
      - libaperture-0-0
    prime:
      - usr/lib/*/libgstgl-1.0.so.0
      - usr/lib/*/libgstgl-1.0.so.0.2001.0
      - usr/lib/*/gstreamer-1.0/libgstopengl.so
      - usr/lib/*/libaperture-0.so.0
      - usr/lib/*/libzbar*

  decoder:
    after:
      - zbar
      - rustup
    plugin: meson
    source: https://gitlab.gnome.org/World/decoder.git
    source-tag: '0.4.1'
    source-depth: 1
    meson-parameters:
      - --prefix=/snap/decoder/current/usr
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    build-packages:
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgstreamer1.0-dev
      - libzbar-dev
      - libssl-dev
    parse-info: [ usr/share/metainfo/com.belmoussaoui.Decoder.metainfo.xml ]
    organize: 
      snap/decoder/current: .

slots:
  decoder:
    interface: dbus
    bus: session
    name: com.belmoussaoui.Decoder

apps:
  decoder:
    command: usr/bin/decoder
    environment:
      SPA_PLUGIN_DIR: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2/
      PIPEWIRE_CONFIG_NAME: $SNAP/usr/share/pipewire/pipewire.conf
      PIPEWIRE_MODULE_DIR: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3
    extensions:
      - gnome
    common-id: com.belmoussaoui.Decoder
    plugs:
      - camera
